import "server-only"

// Generated by scripts/generate-posts-manifest.mjs at build/dev time — no
// filesystem reads happen here, so this works on Cloudflare Workers where
// there's no real fs at request time. Run `pnpm generate:posts` after
// adding or editing a post.
import manifest from "@/content/posts.manifest.json"

export type PostMeta = {
  slug: string
  title: string
  description: string
  date: string
  tags: string[]
  cover?: string
}

type Post = PostMeta & { content: string }

const posts = manifest as Post[]

function toMeta({ content: _content, ...meta }: Post): PostMeta {
  return meta
}

export function getAllPosts(): PostMeta[] {
  return posts.map(toMeta)
}

export function getPost(slug: string): PostMeta | undefined {
  const post = posts.find((p) => p.slug === slug)
  return post ? toMeta(post) : undefined
}

export function getAllTags(): string[] {
  const tags = new Set(getAllPosts().flatMap((post) => post.tags))
  return [...tags].sort()
}

/**
 * Raw markdown rendering of a post, used by the "Copy page as Markdown"
 * and "View as Markdown" post actions (and handy for LLMs).
 */
export function getPostMarkdown(slug: string): string | undefined {
  const post = posts.find((p) => p.slug === slug)
  if (!post) return undefined
  return [
    `# ${post.title}`,
    "",
    `> ${post.description}`,
    "",
    post.content,
    "",
  ].join("\n")
}

/**
 * Rough plain-text rendering of a post body for the WebMCP/search index.
 * Strips JSX tags, code fence markers, markdown syntax, and frontmatter.
 */
export function getPostPlainText(slug: string): string {
  const content = posts.find((p) => p.slug === slug)?.content ?? ""
  return content
    .replace(/<[^>]+>/g, " ")
    .replace(/```[\s\S]*?```/g, (block) =>
      block.replace(/```[^\n]*\n?/g, "").trim(),
    )
    .replace(/!\[([^\]]*)\]\([^)]*\)/g, "$1")
    .replace(/\[([^\]]*)\]\([^)]*\)/g, "$1")
    .replace(/[*_`>#]+/g, "")
    .replace(/\s+/g, " ")
    .trim()
}
